// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TasksApi.Entities
{
    [Table("User")]
    public partial class User
    {
        public User()
        {
            RefreshTokens = new HashSet<RefreshToken>();
            Tasks = new HashSet<Task>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [StringLength(255)]
        public string Password { get; set; }
        [Required]
        [StringLength(255)]
        public string PasswordSalt { get; set; }
        [Required]
        [StringLength(255)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(255)]
        public string LastName { get; set; }
        [Column("TS", TypeName = "smalldatetime")]
        public DateTime Ts { get; set; }
        public bool Active { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<RefreshToken> RefreshTokens { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}